const admin = require('firebase-admin');
const fs = require('fs');

// Initialize Firebase Admin SDK
const serviceAccount = require('./serviceAccountKey.json'); // You'll need to add your service account key

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  projectId: 'annedfinds-9e5b4'
});

const db = admin.firestore();

// Define the 26 comprehensive categories
const categories = [
  {
    name: 'Fashion & Apparel',
    description: 'Clothing and fashion items for all ages and styles',
    iconName: 'fashion',
    colorName: 'pink',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 0,
    slug: 'fashion-apparel',
    seo: {
      title: 'Fashion & Apparel - AnneDFinds',
      description: 'Discover the latest fashion trends and clothing for men, women, and children.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Shoes & Footwear',
    description: 'Comfortable and stylish shoes for every occasion',
    iconName: 'shoes',
    colorName: 'brown',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 1,
    slug: 'shoes-footwear',
    seo: {
      title: 'Shoes & Footwear - AnneDFinds',
      description: 'Find the perfect shoes for men, women, and children.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Bags, Luggage & Travel',
    description: 'Travel essentials and stylish bags for every journey',
    iconName: 'bags',
    colorName: 'teal',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 2,
    slug: 'bags-luggage-travel',
    seo: {
      title: 'Bags, Luggage & Travel - AnneDFinds',
      description: 'Quality bags and travel accessories for your adventures.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Jewelry, Watches & Accessories',
    description: 'Elegant jewelry and accessories to complete your look',
    iconName: 'jewelry',
    colorName: 'purple',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 3,
    slug: 'jewelry-watches-accessories',
    seo: {
      title: 'Jewelry, Watches & Accessories - AnneDFinds',
      description: 'Beautiful jewelry and watches for special occasions.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Beauty, Health & Personal Care',
    description: 'Essential beauty and health products for your wellbeing',
    iconName: 'beauty',
    colorName: 'pink',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 4,
    slug: 'beauty-health-personal-care',
    seo: {
      title: 'Beauty, Health & Personal Care - AnneDFinds',
      description: 'Quality beauty and health products for your daily routine.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Baby, Kids & Maternity',
    description: 'Everything for babies, children, and expecting mothers',
    iconName: 'baby',
    colorName: 'blue',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 5,
    slug: 'baby-kids-maternity',
    seo: {
      title: 'Baby, Kids & Maternity - AnneDFinds',
      description: 'Safe and quality products for babies and children.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Groceries & Gourmet',
    description: 'Fresh groceries and gourmet food items',
    iconName: 'groceries',
    colorName: 'green',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 6,
    slug: 'groceries-gourmet',
    seo: {
      title: 'Groceries & Gourmet - AnneDFinds',
      description: 'Fresh groceries and specialty food items delivered to your door.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Household, Cleaning & Laundry',
    description: 'Essential household and cleaning supplies',
    iconName: 'household',
    colorName: 'blue',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 7,
    slug: 'household-cleaning-laundry',
    seo: {
      title: 'Household, Cleaning & Laundry - AnneDFinds',
      description: 'Keep your home clean with our household supplies.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Home & Living',
    description: 'Decor and essentials to make your house a home',
    iconName: 'home',
    colorName: 'brown',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 8,
    slug: 'home-living',
    seo: {
      title: 'Home & Living - AnneDFinds',
      description: 'Beautiful home decor and living essentials.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Furniture',
    description: 'Quality furniture for every room in your home',
    iconName: 'furniture',
    colorName: 'brown',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 9,
    slug: 'furniture',
    seo: {
      title: 'Furniture - AnneDFinds',
      description: 'Stylish and comfortable furniture for your home.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Kitchen & Appliances',
    description: 'Kitchen essentials and home appliances',
    iconName: 'kitchen',
    colorName: 'red',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 10,
    slug: 'kitchen-appliances',
    seo: {
      title: 'Kitchen & Appliances - AnneDFinds',
      description: 'Modern kitchen appliances and cooking essentials.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Electronics & Mobiles',
    description: 'Latest technology and electronic devices',
    iconName: 'electronics',
    colorName: 'blue',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 11,
    slug: 'electronics-mobiles',
    seo: {
      title: 'Electronics & Mobiles - AnneDFinds',
      description: 'Latest smartphones, gadgets, and electronic devices.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Computers, Office & School',
    description: 'Computer equipment and office supplies',
    iconName: 'office',
    colorName: 'grey',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 12,
    slug: 'computers-office-school',
    seo: {
      title: 'Computers, Office & School - AnneDFinds',
      description: 'Computer equipment and office supplies for work and study.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Gaming & Esports',
    description: 'Gaming gear and accessories for gamers',
    iconName: 'gaming',
    colorName: 'purple',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 13,
    slug: 'gaming-esports',
    seo: {
      title: 'Gaming & Esports - AnneDFinds',
      description: 'Gaming consoles, accessories, and gear for esports.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Sports, Fitness & Outdoors',
    description: 'Sports equipment and outdoor gear',
    iconName: 'sports',
    colorName: 'green',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 14,
    slug: 'sports-fitness-outdoors',
    seo: {
      title: 'Sports, Fitness & Outdoors - AnneDFinds',
      description: 'Sports equipment and outdoor gear for active lifestyles.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Automotive & Moto',
    description: 'Car and motorcycle parts and accessories',
    iconName: 'automotive',
    colorName: 'red',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 15,
    slug: 'automotive-moto',
    seo: {
      title: 'Automotive & Moto - AnneDFinds',
      description: 'Car and motorcycle parts, accessories, and care products.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Home Improvement & Hardware',
    description: 'Tools and materials for home improvement projects',
    iconName: 'tools',
    colorName: 'orange',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 16,
    slug: 'home-improvement-hardware',
    seo: {
      title: 'Home Improvement & Hardware - AnneDFinds',
      description: 'Tools and hardware for DIY and professional projects.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Garden & Outdoor Living',
    description: 'Gardening supplies and outdoor living essentials',
    iconName: 'garden',
    colorName: 'green',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 17,
    slug: 'garden-outdoor-living',
    seo: {
      title: 'Garden & Outdoor Living - AnneDFinds',
      description: 'Plants, gardening tools, and outdoor living accessories.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Pet Supplies',
    description: 'Everything your pets need for health and happiness',
    iconName: 'pets',
    colorName: 'brown',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 18,
    slug: 'pet-supplies',
    seo: {
      title: 'Pet Supplies - AnneDFinds',
      description: 'Food, toys, and supplies for dogs, cats, and other pets.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Books, Media & Music',
    description: 'Books, entertainment media, and musical instruments',
    iconName: 'books',
    colorName: 'indigo',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 19,
    slug: 'books-media-music',
    seo: {
      title: 'Books, Media & Music - AnneDFinds',
      description: 'Books, music, movies, and educational materials.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Hobbies, Collectibles & Crafts',
    description: 'Supplies for hobbies, crafts, and collectibles',
    iconName: 'hobbies',
    colorName: 'purple',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 20,
    slug: 'hobbies-collectibles-crafts',
    seo: {
      title: 'Hobbies, Collectibles & Crafts - AnneDFinds',
      description: 'Craft supplies, collectibles, and hobby materials.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Gifts, Party & Seasonal',
    description: 'Perfect gifts and party supplies for every occasion',
    iconName: 'gifts',
    colorName: 'pink',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 21,
    slug: 'gifts-party-seasonal',
    seo: {
      title: 'Gifts, Party & Seasonal - AnneDFinds',
      description: 'Thoughtful gifts and party supplies for celebrations.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Travel, Tickets & Vouchers',
    description: 'Travel accessories and digital vouchers',
    iconName: 'travel',
    colorName: 'teal',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 22,
    slug: 'travel-tickets-vouchers',
    seo: {
      title: 'Travel, Tickets & Vouchers - AnneDFinds',
      description: 'Travel accessories and digital tickets/vouchers.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Pharmacy & Wellness',
    description: 'Health and wellness products for better living',
    iconName: 'pharmacy',
    colorName: 'green',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 23,
    slug: 'pharmacy-wellness',
    seo: {
      title: 'Pharmacy & Wellness - AnneDFinds',
      description: 'Health products and wellness supplies for better living.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Services',
    description: 'Professional services and repairs',
    iconName: 'services',
    colorName: 'blue',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 24,
    slug: 'services',
    seo: {
      title: 'Services - AnneDFinds',
      description: 'Professional services for repairs and maintenance.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
  {
    name: 'Pre-loved Items',
    description: 'Quality second-hand and refurbished items',
    iconName: 'preloved',
    colorName: 'green',
    isActive: true,
    productCount: 0,
    parentId: null,
    childIds: [],
    level: 0,
    sortOrder: 25,
    slug: 'pre-loved-items',
    seo: {
      title: 'Pre-loved Items - AnneDFinds',
      description: 'Quality second-hand and refurbished products.',
    },
    createdAt: admin.firestore.Timestamp.now(),
    updatedAt: admin.firestore.Timestamp.now(),
  },
];

async function setupCategories() {
  console.log('Starting to setup 26 categories...');

  try {
    // First, clear existing categories to avoid duplicates
    const existingCategories = await db.collection('categories').get();
    console.log(`Found ${existingCategories.docs.length} existing categories. Clearing them...`);
    
    const batch = db.batch();
    existingCategories.docs.forEach((doc) => {
      batch.delete(doc.ref);
    });
    await batch.commit();
    console.log('Existing categories cleared.');

    // Add new categories
    console.log('Adding new 26 categories...');
    const addBatch = db.batch();
    
    categories.forEach((category) => {
      const docRef = db.collection('categories').doc();
      addBatch.set(docRef, category);
    });

    await addBatch.commit();
    console.log('Successfully added all 26 categories to Firestore!');

    // Verify the categories were added
    const newCategories = await db.collection('categories').get();
    console.log(`Verification: ${newCategories.docs.length} categories now in database.`);

  } catch (error) {
    console.error('Error setting up categories:', error);
  } finally {
    process.exit(0);
  }
}

setupCategories();