// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8B1YD9QGVDTVNld9-dXI2HfemNQLUUXs',
    appId: '1:48916413018:web:2c7d9f261b186622f93663',
    messagingSenderId: '48916413018',
    projectId: 'annedfinds',
    authDomain: 'annedfinds.firebaseapp.com',
    storageBucket: 'annedfinds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8B1YD9QGVDTVNld9-dXI2HfemNQLUUXs',
    appId: '1:48916413018:android:7d68edd26925ca4af93663',
    messagingSenderId: '48916413018',
    projectId: 'annedfinds',
    storageBucket: 'annedfinds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8B1YD9QGVDTVNld9-dXI2HfemNQLUUXs',
    appId: '1:48916413018:ios:YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '48916413018',
    projectId: 'annedfinds',
    storageBucket: 'annedfinds.firebasestorage.app',
    iosBundleId: 'com.example.annedfinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8B1YD9QGVDTVNld9-dXI2HfemNQLUUXs',
    appId: '1:48916413018:ios:YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: '48916413018',
    projectId: 'annedfinds',
    storageBucket: 'annedfinds.firebasestorage.app',
    iosBundleId: 'com.example.annedfinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8B1YD9QGVDTVNld9-dXI2HfemNQLUUXs',
    appId: '1:48916413018:web:2c7d9f261b186622f93663',
    messagingSenderId: '48916413018',
    projectId: 'annedfinds',
    authDomain: 'annedfinds.firebaseapp.com',
    storageBucket: 'annedfinds.firebasestorage.app',
  );
}